apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "airflow.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "airflow.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "airflow.serviceAccountName" . }}
  namespace: {{ include "airflow.fullname" . }}
