apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "airflow.fullname" . }}
rules:
{{- if .Values.rbac.events }}
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - "get"
  - "list"
{{- end }}
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "create"
  - "get"
  - "delete"
  - "list"
  - "patch"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "pods/log"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods/exec"
  verbs:
  - "create"
  - "get"
  - "list"