---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-webserver
  labels:
    app.kubernetes.io/name: {{ include "airflow.name" . }}
spec:
  ports:
  - name: airflow-ui
    port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
  selector:
    app.kubernetes.io/name: {{ include "airflow.fullname" . }}-webserver
