---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-scheduler
  labels:
    app.kubernetes.io/name: {{ include "airflow.name" . }}
spec:
  ports:
    - name: airflow-scheduler-task-logs
      protocol: TCP
      port: {{ .Values.scheduler.port }}
      targetPort: {{ .Values.scheduler.port }}
  selector:
    app.kubernetes.io/name: {{ include "airflow.fullname" . }}-scheduler

